### ISSUE TITLE
Missing class files

### ISSUE THREAD

**Issue by kreutzr** [orladigital/trivy-maven-plugin#21]
Hi
Since there is only source code released we built the project with the delivered pom.xml .

I have put the plugin into a profile named "dependencyCheck" in our company's project.

When I run (as described in the project description)

`mvn br.com.orla:trivy-maven-plugin:trivy-scan -P dependencyCheck`

I receive the following error:

```
[ERROR] Failed to execute goal br.com.orla:trivy-maven-plugin:1.0.0:trivy-scan (default-cli) on project tms_parent: Execution default-cli of goal br.com.orla:trivy-maven-plugin:1.0.0:trivy-scan failed: A required class was missing while executing br.com.orla:trivy-maven-plugin:1.0.0:trivy-scan: com/google/common/io/Files
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>br.com.orla:trivy-maven-plugin:1.0.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/rkreutz/.m2/repository/br/com/orla/trivy-maven-plugin/1.0.0/trivy-maven-plugin-1.0.0.jar
[ERROR] urls[1] = file:/C:/Users/rkreutz/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : com.google.common.io.Files
```

**Comment by netodevel-orla** [comment]
hi @kreutzr, let's examine the error.

**Comment by kreutzr** [comment]
ReHi @netodevel-orla . Thanks for looking after that. I hope to find some time tomorrow to check, if the plugin is still there. I'll let you know :) But it would be helpful to find the plugin e.g. here (https://mvnrepository.com/search?q=plugin&c=maven-plugins).

**Comment by netodevel-orla** [comment]
@kreutzr, 
We will publish to maven in the near future when we have a more final version.
Would it help if we published it on the github package registry?

**Comment by kreutzr** [comment]
Dear José

It turned out, that this issue addresses a "user" problem (meaning that I was just the wrong person to test) 😉
Feel free to close the issue.
A collegue gave it a try and it worked right from the start.
We will follow your project since I like your idea of checking the images in use.

Have a nice week

Best regards

Reinhard


________________________________
Von: José Vieira Neto ***@***.***>
Gesendet: Freitag, 26. Januar 2024 16:58
An: orladigital/trivy-maven-plugin ***@***.***>
Cc: Reinhard Kreutz ***@***.***>; Mention ***@***.***>
Betreff: Re: [orladigital/trivy-maven-plugin] Missing class files (Issue #21)


@kreutzr<https://github.com/kreutzr>,
We will publish to maven in the near future when we have a more final version.
Would it help if we published it on the github package registry?

**Comment by netodevel-orla** [comment]
I'll close then.
There will be developments in this project soon.
Thanks for the feedback.

**Comment by netodevel-orla** [comment]
Hi @kreutzr, 
The plugin is now available on maven central for download :rocket: and we have also added the ability to choose the trivy binary version.

Enjoy and share

```xml
 <plugin>
      <groupId>tech.orla</groupId>
      <artifactId>trivy-maven-plugin</artifactId>
      <version>1.0.1</version>
          <configuration>
              <vulnType>os,library</vulnType>
              <severity>HIGH,CRITICAL</severity>
              <ignoreUnfixed>true</ignoreUnfixed>
              <trivyVersion>v0.49.1</trivyVersion>
          </configuration>
      <executions>
          <execution>
              <goals>
                  <goal>trivy-scan</goal>
              </goals>
          </execution>
      </executions>
</plugin>
```
